In [1]:
speed = [12, 13,17, 11]
duration = [30, 55, 2, 4]

In [2]:
result = speed/duration

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [3]:
speed = [12, 13, 17, 11]
duration = [30, 55, 2, 4]

In [4]:
# import required library
import numpy as np

In [8]:
# create speed and duration Numpy arrays
np_speed = np.array(speed)
np_duration = np.array(duration)

In [9]:
distance = np_speed/np_duration

In [10]:
distance

array([0.4       , 0.23636364, 8.5       , 2.75      ])

# Classes and Attributes of ndarray: ndim

In [12]:
np_car = np.array(['Volvo','Camry','Benz','Range'])

In [13]:
np_car.ndim

1

In [14]:
np_car_with_color = np.array([['Volvo','Camry','Benz','Range'],['red', 'orange', 'yellow', 'blue']])

In [15]:
np_car_with_color.ndim

2

# Classes and Attributes of ndarray: shape

In [16]:
np_car.shape

(4,)

In [17]:
np_car_with_color.shape

(2, 4)

# Classes and Attributes of ndarray: size

In [18]:
np_car.size

4

In [19]:
np_car_with_color.size

8

# Classes and Attributes of ndarray: dtype

In [20]:
np_car

array(['Volvo', 'Camry', 'Benz', 'Range'], dtype='<U5')

In [21]:
np_car.dtype

dtype('<U5')

# Basic Operations

In [22]:
first_car_owners = [12,15,7,9]

In [23]:
second_car_owners = [5,10,13,19]

In [24]:
np_first_car_owners = np.array(first_car_owners)

In [25]:
np_second_car_owners = np.array(second_car_owners)

In [26]:
np_first_car_owners+np_second_car_owners

array([17, 25, 20, 28])

# Access Array Element: Indexing

In [32]:
# create 2D array
cars_owned = np.array([[12,15,7,9],[5,10,13,19]])

In [33]:
cars_owned[0]

array([12, 15,  7,  9])

In [34]:
cars_owned[1]

array([ 5, 10, 13, 19])

In [35]:
cars_owned[0][1]

15

In [38]:
cars_owned[:,1]

array([15, 10])

# Accessing Array Elements: Slicing

In [39]:
cars_owned

array([[12, 15,  7,  9],
       [ 5, 10, 13, 19]])

In [40]:
cars_owned.shape

(2, 4)

In [42]:
range_cars_owned = cars_owned[:,1:3]

In [43]:
range_cars_owned

array([[15,  7],
       [10, 13]])

In [44]:
new_array = np.array([6, 8, 10, 20])

In [45]:
new_array[0:2]

array([6, 8])

# Accessing Array Elements: Iteration

In [46]:
cars_owned

array([[12, 15,  7,  9],
       [ 5, 10, 13, 19]])

In [47]:
for car in cars_owned:
    print(car)

[12 15  7  9]
[ 5 10 13 19]


# Indexing with Boolean Arrays

In [48]:
maths_score = np.array([[35,67,83,47],[58,67,92,45]])

In [50]:
passed_score = maths_score>50

In [51]:
passed_score

array([[False,  True,  True, False],
       [ True,  True,  True, False]])

In [53]:
maths_score[passed_score]

array([67, 83, 58, 67, 92])

# Copy and views

In [55]:
States = np.array(['Abia','Imo','Enugu','Zamfara','Abuja','Lagos'])

In [56]:
States

array(['Abia', 'Imo', 'Enugu', 'Zamfara', 'Abuja', 'Lagos'], dtype='<U7')

In [57]:
Total_states = States

In [58]:
Total_states

array(['Abia', 'Imo', 'Enugu', 'Zamfara', 'Abuja', 'Lagos'], dtype='<U7')

In [59]:
Total_states is States

True

In [60]:
Total_states

array(['Abia', 'Imo', 'Enugu', 'Zamfara', 'Abuja', 'Lagos'], dtype='<U7')

In [61]:
view_total_states = Total_states.view()

In [62]:
len(view_total_states)

6

In [63]:
# change value in the view object
view_total_states[1] = "Benue"

In [64]:
view_total_states

array(['Abia', 'Benue', 'Enugu', 'Zamfara', 'Abuja', 'Lagos'], dtype='<U7')

In [65]:
# original dataset
Total_states

array(['Abia', 'Benue', 'Enugu', 'Zamfara', 'Abuja', 'Lagos'], dtype='<U7')

In [66]:
copy_states = States.copy()

In [67]:
copy_states is States

False

In [68]:
States[3] = 'Niger'

In [69]:
States

array(['Abia', 'Benue', 'Enugu', 'Niger', 'Abuja', 'Lagos'], dtype='<U7')

In [71]:
copy_states

array(['Abia', 'Benue', 'Enugu', 'Zamfara', 'Abuja', 'Lagos'], dtype='<U7')

# Universal Functions(ufunc)

In [72]:
# find the square root of the following numbers
np_sqrt = np.sqrt([2,9,16,64])

In [73]:
np_sqrt

array([1.41421356, 3.        , 4.        , 8.        ])

In [74]:
# import pi
from numpy import pi

In [75]:
np.cos(0)

1.0

In [76]:
np.sin(pi/2)

1.0

In [77]:
np.cos(pi)

-1.0

In [78]:
np.floor([1.6,2.7,3.2,1.1,-0.4])

array([ 1.,  2.,  3.,  1., -1.])

In [79]:
np.exp([0,1,4])

array([ 1.        ,  2.71828183, 54.59815003])

# shape manipulation

In [80]:
new_numbers = np.array([[12,11,34,54,34,23],[3,54,23,65,67,12]])

In [83]:
new_numbers

array([[12, 11, 34, 54, 34, 23],
       [ 3, 54, 23, 65, 67, 12]])

In [81]:
# flatten the dataset
new_numbers.ravel()

array([12, 11, 34, 54, 34, 23,  3, 54, 23, 65, 67, 12])

In [86]:
# reshapes the dataset to 3 rows and 4 columns
new_numbers.reshape(6,2)

array([[12, 11],
       [34, 54],
       [34, 23],
       [ 3, 54],
       [23, 65],
       [67, 12]])

In [87]:
# resign again to 2 rows and 6 columns
new_numbers.resize(2,6)

In [88]:
new_numbers

array([[12, 11, 34, 54, 34, 23],
       [ 3, 54, 23, 65, 67, 12]])

In [90]:
# split the array into two
np.hsplit(new_numbers,2)

[array([[12, 11, 34],
        [ 3, 54, 23]]),
 array([[54, 34, 23],
        [65, 67, 12]])]

In [91]:
stack1 =np.array([12,11,34,54,34,23])
stack2 = np.array([3,54,23,65,67,12])

In [93]:
np.hstack((stack1,stack2))

array([12, 11, 34, 54, 34, 23,  3, 54, 23, 65, 67, 12])

# Broadcasting

In [94]:
# create two arrays of the same type
array1 = np.array([2,3,4,5])
array2 = np.array([6,7,8,9])

In [95]:
array1 * array2

array([12, 21, 32, 45])

In [96]:
array3 = 3

In [97]:
array1 * array3

array([ 6,  9, 12, 15])

# Broadcasting constraint

In [98]:
array4 = np.array([5,6])

In [99]:
array1 * array4

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [100]:
np_workers_per_day1 = np.array([23, 123, 176, 183])
np_workers_per_day2 = np.array([35, 163, 156, 144])

In [101]:
total_earning = np_workers_per_day1+np_workers_per_day2

In [103]:
total_earning/15

array([ 3.86666667, 19.06666667, 22.13333333, 21.8       ])

# Transpose

In [104]:
test_score = np.array([[83,71,45,56],[45,67,87,89]])

In [105]:
test_score

array([[83, 71, 45, 56],
       [45, 67, 87, 89]])

In [106]:
test_score.transpose()

array([[83, 45],
       [71, 67],
       [45, 87],
       [56, 89]])

In [110]:
# Inverse and Trace Function
price = np.array([[10,20],[15,25]])

In [111]:
np.linalg.inv(price)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [113]:
price

array([[10, 20],
       [15, 25]])

In [112]:
#  trace function
np.trace(price)

35